### ISSUE TITLE
Wrapper Code

### ISSUE THREAD

**Issue by karacanil** [BobMcDear/Attention-in-Vision#1]
Hey,

Great work with the repository. But a wrapper code that allows users to observe the implemented attention techniques in practice would be a great addition to this repository.

Have a great day.

**Comment by BobMcDear** [comment]
Hello,

Thank you for your interest. I am not sure what you mean by "observe the implemented attention techniques". Are you referring to a visualization toolbox for the attention mechanisms in this repository?

Best,
Borna
